### ISSUE TITLE
Feature request: switching tabs with Cmd+1..9

### ISSUE THREAD

**Issue by voxpuibr** [hetima/SafariStand#16]
Hi, first of all, thank you for your work! The ability to see favicons in tabs is priceless and makes Safari much more of an acceptable browser.

I was wondering if you could consider adding the feature of switching tabs in current window by number shortcuts, like "Cmd+1" for first tab, "Cmd+2" for second and so on?

**Comment by hetima** [comment]
implemented in 8.0.210.
Thanks for suggestion.

**Comment by voxpuibr** [comment]
Wow, that was quick. Thanks!

Please let me now if I can help with anything: programming or english translations, for example.
