### ISSUE TITLE
Feature Request: Reopening last closed tabs

### ISSUE THREAD

**Issue by wiruzx** [hetima/SafariStand#17]
Currently it is possible only to reopen one last closed tab via `CMD+Z`

**Comment by vjpr** [comment]
It would be great if we could replicate Chrome behaviour where consecutive presses of `Cmd+Shift+T` reopen each previous tab (including history so the back button works).

**Comment by hetima** [comment]
implemented in 8.0.212
thanks  

Menu item appears in Stand menu. Shortcut is not assigned (`Cmd+Shift+T` is assigned to toggle tab bar). Customize shortcut in System Preferences > Keyboard if you want.

**Comment by wiruzx** [comment]
Awesome, thanks!
