### ISSUE TITLE
Feature request:  Will pinned tabs ever be a possibility?

### ISSUE THREAD

**Issue by giantspeck** [hetima/SafariStand#21]
I am a very long time Firefox user and occasional Chrome user and my must have feature of either browser is the ability to "pin" tabs for frequently visited websites so that only the favicon for the website appears.

Is adding this functionality to Safari via SafariStand within the realm of possibility?  If this feature could somehow be achieved in Safari, I would seriously consider switching to Safari because the browsing experience in Safari is just that much faster.

![firefox-screenshot](https://cloud.githubusercontent.com/assets/8790458/8007175/cc6be2ea-0b35-11e5-89ee-92b0d9b9bc23.png)

**Comment by giantspeck** [comment]
Nevermind!  It appears that this functionality will be added to the new version of Safari which will be included with OS X El Capitan!

**Comment by hetima** [comment]
yeah
