### ISSUE TITLE
What does the new "Keep Closed Tab for Reopen" feature do?

### ISSUE THREAD

**Issue by Fofer** [hetima/SafariStand#24]
I'm not sure I understand this setting and the number options in the pulldown.  Is it automatic or does it give a new command to manually re-open recently closed tabs?

**Comment by hetima** [comment]
Reopen closed tab from Stand menu.

![2015-06-17 19 05 17](https://cloud.githubusercontent.com/assets/33700/8204523/3ace1ec2-1524-11e5-8577-3437e0bc4b12.png)

**Comment by Fofer** [comment]
That is awesome!  Thanks so much!
