### ISSUE TITLE
Clicking a tab in the tab bar opens a new tab instead

### ISSUE THREAD

**Issue by mdlinville** [hetima/SafariStand#49]
Version 9.0.217Yosemite on El Capitan. When I try to click any tab in the tab bar, it opens a new empty tab! The only way to get back to a previous tab is to cmd+w to close all the ones in 'front' of it. Here are my settings:
![screen shot 2015-12-10 at 11 39 03 am](https://cloud.githubusercontent.com/assets/7674613/11726260/abd2d282-9f32-11e5-88d6-eff9845658f7.png)

**Comment by ej8** [comment]
To stop this unwanted tab opening behavior you have to uncheck "Suppress Tab Bar Width".  Not ideal but it stops it from happening.

**Comment by Fofer** [comment]
For what it's worth, I'm NOT seeing this behavior on my system (also Version 9.0.217Yosemite on El Capitan.)  I am able to click a tab and it doesn't open a new tab.  And yes, I have "Suppress Tab Bar Width" checked, as well.

**Comment by craftey** [comment]
Here it happens, when I have a pinned tab (fixed tab). Clicking on the last normal tab opens a new one. So I think this issue is related to another issue https://github.com/hetima/SafariStand/issues/45
